[package]
name = "lumodb"
version = "0.1.0"
edition = "2021"

[dependencies]
bitflags = "2.4.1"
log = "0.4.26"
memmap2 = "0.9.0"
thiserror = "1.0"
lazy_static = "1.4.0"
once_cell = "1.18"

[dev-dependencies]
tempfile = "3.8"
